function test(A,f,N,VDC)
fig=figure( ...
           'Name','Proiect', ...
           'NumberTitle','off', ...
           'Units','Normalized',...
           'Visible','on',...
           'color','#f2e4e7',...
           'Position',[0.03 0.03 0.8 0.8]);
       
T=1/f;
t=0:T/100:N*T;
w=2.*pi.*f; 
cos=0;

BA=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.8 0.8 .03 .02],...
              'backgroundcolor','#d3d3d3',...
              'fontsize', 10,...
              'foregroundcolor','black',...
              'String','A=');

BAe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.83 0.8 .04 .025],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',A,...
            'fontsize', 10,...
            'Tag','tens_A',...
            'Callback','A=str2num(get(gco,''string''));close;test(A,f,N,VDC)');
        
        
        Bf=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.8 0.75 .03 .02],...
              'backgroundcolor','#d3d3d3',...
              'fontsize', 10,...
              'foregroundcolor','black',...
              'String','f=');

Bfe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.83 0.75 .04 .025],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',f,...
            'fontsize', 10,...
            'Tag','tens_f',...
            'Callback','f=str2num(get(gco,''string''));close;test(A,f,N,VDC)');
        
          
        BN=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.8 0.7 .03 .02],...
              'backgroundcolor','#d3d3d3',...
              'fontsize', 10,...
              'foregroundcolor','black',...
              'String','N=');

BNe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.83 0.7 .04 .025],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',N,...
            'fontsize', 10,...
            'Tag','tens_N',...
            'Callback','N=str2num(get(gco,''string''));close;test(A,f,N,VDC)');
        
        
        %SEMNAL SINUSOIDAL
        Vi=A*sin(w*t);
        subplot(3,3,1);
plot(t,Vi,'-r');
grid on;
title('Semnalul Sinusoidal','FontSize',13);
xlabel('timp[ms]');
ylabel('Amplitudine [V]');


z=uicontrol('Style','Checkbox',...
 'Units','normalized',...
 'String','COSINUS',...
 'BackgroundColor','#d3d3d3',...
 'Position', [0.6 .7 .1 .1],...
 'Callback','cos=1;close;test(A,f,N,VDC)')



switch cos
    case 1
  subplot(3,3,1);
plot(t,Vi,'-r');
grid on;
title('Semnalul cos','FontSize',13);
xlabel('timp[ms]');
ylabel('Amplitudine [V]');
    case 2
 subplot(3,3,1);
plot(t,Vi,'-r');
grid on;
title('Semnalul Sinusoidal','FontSize',13);
xlabel('timp[ms]');
ylabel('Amplitudine [V]');
end
        
if cos==1
   % Vi=A*sin(w*t)+pi/2;
   set(z,'value',1)
    set(z,'value',0)
  
else
     %  Vi=A*sin(w*t);
      set(z,'value',0)
       set(z,'value',1)
     
 
end

 BVDC=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.8 0.6 .03 .02],...
              'backgroundcolor','#d3d3d3',...
              'fontsize', 10,...
              'foregroundcolor','black',...
              'String','VDC=');

BVDCe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.83 0.6 .04 .025],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',VDC,...
            'fontsize', 10,...
            'Tag','tens_VDC',...
            'Callback','VDC=str2num(get(gco,''string''));close;test(A,f,N,VDC)');
        
        %semnal DC
        

dc=VDC+A*sin(2*pi*f*t);
subplot(3,3,7);
plot(t,dc,'-r');
grid on;
title('Semnalul DC','FontSize',13);
xlabel('timp[ms]');
ylabel('Amplitudine [V]');







